// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aipdutbeaxkdwbugsyaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpcGR1dGJlYXhrZHdidWdzeWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MDMwOTUsImV4cCI6MjA1MDQ3OTA5NX0.AvMyIpshaIA9p4XDbQtDasN1H_YtpoMiUVHyAFSt9k8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);